### ISSUE TITLE
你的这个cpu跑分有点太低了，应该是你的cupFrind.kext不太对

### ISSUE THREAD

**Issue by qunqunzq** [mengxyz/Hackintosh_Asrock_H670_PG_RIPTIDE_13600K#1]
我的13400f，单核心都能到2千多

**Comment by mengxyz** [comment]
@qunqunzq  Thank you for information. 
Its copy paste version i am beginner hackintosh.
I find many CpuFriendDataProvider.

Its correct now?
https://browser.geekbench.com/v5/cpu/20781562

**Comment by qunqunzq** [comment]
It looks pretty much the same now.
It is mainly that the maximum frequency of cpu Rui frequency affects the performance, which has a certain relationship with cupFrind's fake mac models.
You are from Thailand. I thought your name was Chinese。。。
